services:
  # Aplicação principal
  estatistica-transacao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estatistica-transacao-app
    ports:
      - "8080:8080"
    environment:
      # Configurações da aplicação
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC
      # Configurações de logging
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_BR_COM_ITAU=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage: